ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'ADMIN' BEFORE 'TEACHER';

ALTER TABLE "User"
ADD COLUMN "passwordHash" TEXT,
ADD COLUMN "passwordChangedAt" TIMESTAMP(3),
ADD COLUMN "authVersion" INTEGER NOT NULL DEFAULT 0;
